import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { ContactService } from '../../../Services/contact-service.service';  // Assuming this is your contact service

@Component({
  selector: 'app-add-contact',
  templateUrl: './add-contact.component.html',
  styleUrls: ['./add-contact.component.css']
})
export class AddContactComponent implements OnInit {

  contactForm!: FormGroup;
  isSuccess: boolean = false;
  showMessage: boolean = false;
  message: string = '';

  constructor(
    private fb: FormBuilder,
    private contactService: ContactService,  // Injecting the contact service
    private router: Router
  ) {}

  ngOnInit(): void {
    this.contactForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      numTel: ['', [Validators.required, Validators.pattern('[0-9]{10}')]],
      fax: ['', [Validators.pattern('[0-9]{10}')]],  // Fax is optional but should match the pattern
      idLaboratoire: ['', Validators.required]  // Lab ID is required
    });
  }

  // Form submission handler
  onSubmit(): void {
    if (this.contactForm.valid) {
      const contactData = {
        id: null,  // Assuming ID is generated by the backend
        email: this.contactForm.value.email,
        numTel: this.contactForm.value.numTel,
        fax: this.contactForm.value.fax || '',  // Set to an empty string if fax is not provided
        idLaboratoire: this.contactForm.value.idLaboratoire,
      };

      // Send the contact data to the backend via the contact service
      this.contactService.addContact(contactData).subscribe({
        next: (response) => {
          this.message = 'Contact créé avec succès !';
          this.isSuccess = true;
          this.showMessage = true;
          console.log('Contact créé avec succès', response);

          // Hide the success message after 5 seconds
          setTimeout(() => {
            this.showMessage = false;
            this.router.navigate(['/list-contact']);
          }, 5000);
        },
        error: (error) => {
          this.message = `Erreur lors de la création du contact : ${error.error?.message || error.message}`;
          this.isSuccess = false;
          this.showMessage = true;
          console.error('Erreur:', error);

          // Hide the error message after 5 seconds
          setTimeout(() => {
            this.showMessage = false;
          }, 5000);
        },
      });
    }
  }

}
