services:
  discovery-service:
    build: ProjetLibreBack/discovery-service
    container_name: discovery-service-container
    ports:
      - '8761:8761'
    expose:
      - '8761'
  gateway-service:
    build: ProjetLibreBack/gateway-service
    container_name: gateway-service-container
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      - discovery-service
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: labo_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  labo-service:
    build: ProjetLibreBack/labo-service
    container_name: labo-service-container
    ports:
      - '8082:8082'
    expose:
      - '8082'
    depends_on:
      - database
      - discovery-service

  database-analyse:
    image: postgres:latest
    environment:
      POSTGRES_DB: analyse_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
  analyse-service:
    build: ProjetLibreBack/analyse-service
    container_name: analyse-service-container
    ports:
      - '8083:8083'
    expose:
      - '8083'
    depends_on:
      - database-analyse
      - discovery-service

  database-contactlabo:
    image: postgres:latest
    environment:
      POSTGRES_DB: contactlabo_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
  contactlabo-service:
    build: ProjetLibreBack/contactLabo-service
    container_name: contactlabo-service-container
    ports:
      - '8084:8084'
    expose:
      - '8084'
    depends_on:
      - database-contactlabo
      - discovery-service

  database-adresse:
    image: postgres:latest
    environment:
      POSTGRES_DB: adresse_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5435:5432"
  adresse-service:
    build: ProjetLibreBack/adresse-service
    container_name: adresse-service-container
    ports:
      - '8089:8089'
    expose:
      - '8089'
    depends_on:
      - database-adresse
      - discovery-service

  frontend:
    build:
      context: ./ProjetLibreFront/projetfront
    container_name: frontend-app
    ports:
      - "4200:4200"
    depends_on:
      - gateway-service
