services:
  discovery-service:
     build: ProjetLibreBack/discovery-service
     container_name: discovery-service-container
     ports:
       - '8761:8761'
     expose:
       - '8761'
  gateway-service:
    build: ProjetLibreBack/gateway-service
    container_name: gateway-service-container
    ports:
      - '8888:8888'
    expose:
      - '8888'
    depends_on:
      - discovery-service
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: labo_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  labo-service:
    build: ProjetLibreBack/labo-service
    container_name: labo-service-container
    ports:
      - '8082:8082'
    expose:
      - '8082'
    depends_on:
      - database
      - discovery-service