version: '3.8'

services:
  discovery-service:
    build: ProjetLibreBack/discovery-service
    container_name: discovery-service-container
    ports:
      - '8761:8761'

  gateway-service:
    build: ProjetLibreBack/gateway-service
    container_name: gateway-service-container
    ports:
      - '8888:8888'
    depends_on:
      - discovery-service

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: labo_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  labo-service:
    build: ProjetLibreBack/labo-service
    container_name: labo-service-container
    ports:
      - '8082:8082'
    depends_on:
      - database
      - discovery-service

  database-analyse:
    image: postgres:latest
    environment:
      POSTGRES_DB: analyse_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"

  analyse-service:
    build: ProjetLibreBack/analyse-service
    container_name: analyse-service-container
    ports:
      - '8083:8083'
    depends_on:
      - database-analyse
      - discovery-service

  database-contactlabo:
    image: postgres:latest
    environment:
      POSTGRES_DB: contactlabo_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"

  contactlabo-service:
    build: ProjetLibreBack/contactLabo-service
    container_name: contactlabo-service-container
    ports:
      - '8084:8084'
    depends_on:
      - database-contactlabo
      - discovery-service

  database-adresse:
    image: postgres:latest
    environment:
      POSTGRES_DB: adresse_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5435:5432"

  adresse-service:
    build: ProjetLibreBack/adresse-service
    container_name: adresse-service-container
    ports:
      - '8089:8089'
    depends_on:
      - database-adresse
      - discovery-service

  database-dossier:
    image: postgres:latest
    environment:
      POSTGRES_DB: dossier_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5436:5432"

  dossier-service:
    build: ProjetLibreBack/dossier-service
    container_name: dossier-service-container
    ports:
      - '8087:8087'
    depends_on:
      - database-dossier
      - discovery-service

  database-epreuve:
    image: postgres:latest
    environment:
      POSTGRES_DB: epreuve_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5437:5432"

  epreuve-service:
    build: ProjetLibreBack/epreuve-service
    container_name: epreuve-service-container
    ports:
      - '8085:8085'
    depends_on:
      - database-epreuve
      - discovery-service

  database-examen:
    image: postgres:latest
    environment:
      POSTGRES_DB: examen_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5438:5432"

  examen-service:
    build: ProjetLibreBack/examen-service
    container_name: examen-service-container
    ports:
      - '8088:8088'
    depends_on:
      - database-examen
      - discovery-service

  database-patient:
    image: postgres:latest
    environment:
      POSTGRES_DB: patient_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5439:5432"

  patient-service:
    build: ProjetLibreBack/patient-service
    container_name: patient-service-container
    ports:
      - '8086:8086'
    depends_on:
      - database-patient
      - discovery-service

  database-testanalyse:
    image: postgres:latest
    environment:
      POSTGRES_DB: testanalyse_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5440:5432"

  testanalyse-service:
    build: ProjetLibreBack/testAnalyse-service
    container_name: testanalyse-service-container
    ports:
      - '8091:8091'
    depends_on:
      - database-testanalyse
      - discovery-service

  database-utilisateur:
    image: postgres:latest
    environment:
      POSTGRES_DB: utilisateur_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5441:5432"

  utilisateur-service:
    build: ProjetLibreBack/utilisateur-service
    container_name: utilisateur-service-container
    ports:
      - '8090:8090'
    depends_on:
      - database-utilisateur
      - discovery-service

  frontend:
    build:
      context: ./ProjetLibreFront/projetfront
    container_name: frontend-app
    ports:
      - "4200:4200"
    depends_on:
      - gateway-service
